const cartActionTypes = {
   TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
   ADD_ITEM: 'ADD_ITEM',
   REMOVE_ITEM: 'REMOVE_ITEM',
   CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
   CLEAR_CART: 'CLEAR_CART',
   UPDATE_CART_START: 'UPDATE_CART_START',
   UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
   UPDATE_CART_FAILED: 'UPDATE_CART_FAILED',
   UPDATE_CART_ON_SIGN_IN_START: 'UPDATE_CART_ON_SIGN_IN_START'
};

export default cartActionTypes;