const userActionTypes = {
   GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
   EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
   SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
   ACTION_FAILED: 'ACTION_FAILED',
   SIGNOUT_START: 'SIGNOUT_START',
   SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS', 
   SIGNUP_START: 'SIGNUP_START',
   SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
   CHECK_USER_SESSION: 'CHECK_USER_SESSION'
};

export default userActionTypes;